version: '3'
services:
  # api:
  #   # ignore node_modules folder on build context    
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - NODE_ENV=production
  #   # mount local folder to container
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgresdb
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: unidos
      POSTGRES_PASSWORD: gloriacristo
      POSTGRES_DB: unidos_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

