version: '3'
services:
  nestapi:
    container_name: nestapi
    build: .
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    env_file:
      - .env
    depends_on:
      - postgresdb
    networks:
      - mynetwork
  postgresdb:
    container_name: pg
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${EXTERNAL_DB_PORT}:${INTERNAL_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${EXTERNAL_PGADMIN_PORT}:${INTERNAL_PGADMIN_PORT}
    networks:
      - mynetwork
    depends_on:
      - postgresdb
volumes:
  postgres-data:
networks:
  mynetwork:
    driver: bridge
